version = 2
[plugins]
  [plugins."io.containerd.grpc.v1.cri".containerd]
    default_runtime_name = "runc"
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        # runc: https://github.com/runc
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            Path = "runc"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  # 'plugins."io.containerd.grpc.v1.cri".cni' contains config related to cni
  [plugins."io.containerd.grpc.v1.cri".cni]
    # bin_dir is the directory in which the binaries for the plugin is kept.
    bin_dir = "../../bin/cni"
    # conf_dir is the directory in which the admin places a CNI conf.
    conf_dir = "../../config/cni"
